Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AlignParameters:
  Enabled: with_fixed_indentation

Style/DotPosition:
  EnforcedStyle: trailing

Style/NumericLiterals:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/Documentation:
  Enabled: false
